language: java
jdk:
  - oraclejdk8
deploy:
  # deploy develop to the staging environment
  - provider: script
    script: deploy.sh staging
    on:
      branch: dev
  # deploy master to production
  - provider: script
    script: deploy.sh production
    on:
      branch: master
