cache:
  directories:
  - $HOME/.m2/repository/org/bukkit/craftbukkit
before_install: | # Wget BuildTools and run if cached folder not found
  if [ ! -d "$HOME/.m2/repository/org/bukkit/craftbukkit/1.12-R0.1-SNAPSHOT" ]; then
  wget -O BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
  java -jar BuildTools.jar --rev 1.12
  fi

language: java
jdk:
  - oraclejdk8
deploy:
  # deploy develop to the staging environment
  - provider: script
    script: deploy.sh staging
    on:
      branch: dev
  # deploy master to production
  - provider: script
    script: deploy.sh production
    on:
      branch: master
